---
- name: "Create a VM from  template"
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    # - name: Include vars file
    #   include_vars: vars.yml

    - name: "Clone the template"
      vmware_guest:
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        template: "Server-{{ os_version }}-Template"
        validate_certs: false
        cluster: "{{ cluster }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ vmfolder }}"
        state: poweredon
        datastore: "{{ datastore }}"
        annotation: "{{ description }} - Server Setup: {{ '%m-%d-%Y' | strftime }}"
        name: "{{ server_name|upper }}"
        networks:
          - name: "{{ vmnetname }}"
            device_type: vmxnet3
            ip: "{{ serverip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            dns_servers:
            - "{{ dns1 }}"
            - "{{ dns2 }}"
        hardware:
            memory_mb: "{{ ram *1024 }}"
            num_cpus: "{{ cpu_cores }}"
            num_cpu_cores_per_socket: "{{ cpu_cores }}"
            hotadd_cpu: True
            hotremove_cpu: True
            hotadd_memory: True
        customization:
          domain: "{{ domain }}"
          domainadmin: "{{ domain_username }}"
          domainadminpassword: "{{ domain_password }}"
          fullname: " {{ domain }}"
          orgname: "{{ domain }}"
          joindomain: "{{ domain }}"
          timezone: "{{ tz }}"
          autologon: True
          password: '{{ localwin_password }}'
          runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1
        wait_for_customization: 'Yes'
        wait_for_ip_address: 'Yes'

    - name: Wait for 10 Seconds
      wait_for:
        timeout: 10

    - name: Add Server to host Inventory
      add_host:
        name: "{{ server_name }}"
        ansible_port: 5986
        ansible_user: "{{ domain_username }}"
        ansible_password: "{{ domain_password }}"
        ansible_winrm_server_cert_validation: ignore
        ansible_connection: "winrm"
        ansible_winrm_transport: kerberos
      # no_log: true

    - name: Add DC to host Inventory
      add_host:
        name: "{{ dcname }}"
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5986
        ansible_user: "{{ domain_username }}"
        ansible_password: "{{ domain_password }}"
        ansible_connection: "winrm"
        ansible_winrm_transport: kerberos
      # no_log: true

    - name: Move AD Computer
      win_domain_computer:
        name: "{{ server_name|upper }}"
        dns_hostname: "{{ server_name|upper }}.{{ domain }}"
        ou: "{{ OU }}"
        description: "{{ description }}"
        enabled: yes
        state: present
      delegate_to: "{{ dcname }}"

    - name: Setup DNS
      win_dns_record:
        name: "{{ server_name |upper }}"
        type: "A"
        value: "{{ serverip }}"
        zone: "{{ domain }}"
      delegate_to: "{{ dcname }}"


    - name: Set registry key for computer description
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
        name: srvcomment
        data: "{{ description }}"
      delegate_to: "{{ server_name }}"


    - name: Restart Computer
      win_reboot:
      delegate_to: "{{ server_name }}"